FROM node:20-alpine

WORKDIR /app

COPY package*.json ./
RUN npm install --only=production

COPY src ./src

ENV NODE_ENV=production
ENV MOCK_SERVICE_PORT=4000

EXPOSE 4000

CMD ["node", "src/mock_service/app.js"]
